version: '3'
services:
  angular: 
    image: node:18
    ports:
    - 4200:4200
    dns:
    - 8.8.8.8
    - 1.1.1.1
    volumes:
      - ./angular:/code
    command:
      - /bin/bash
      - -c
      - | 
        cd /code
        npm install -g @angular/cli 
        ng serve --host 0.0.0.0 --port 4200
  app:
    image: python:3.11
    ports: 
      - 8080:8080
    volumes:
      - .:/code
    env_file:
      - env/local.env
    environment:
      - FLASK_DEBUG=true
    dns:
      - 8.8.8.8
      - 1.1.1.1
    network_mode: bridge
    command:
      - /bin/bash
      - -c
      - |
        cd /code
        pip install --upgrade pip && pip install poetry
        poetry config virtualenvs.create false
        poetry install
        
        python -m uvicorn training_tracking.api.main:app --host 0.0.0.0 --port 8080 --reload
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file:
      - env/local.env
    ports: 
      - 5432:5432
    volumes:
      - ./pgData:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080
    depends_on:
      - postgresdb
